### PR TITLE
Add: Add XIAO nRF52840 symbol to `Seeed_Studio_XIAO_Series.kicad_sym`.

### PR DESCRIPTION
**Pull request by ndoo**
Could not confirm from pinout diagram which NFC pad is NFC1/NFC2 but should not impact usage for NFC antenna.

### CODE REVIEW

**Comment by ndoo** [comment]
Hello?

**Review by MatthewJeffson — APPROVED** [review]
企业微信截图_b0a2d9e6-5670-412f-9ae8-80bf785bae1a

NICE work!

Best Regards,
Matthew

**Comment by limengdu** [comment]
Thanks for submitting this pull request to add a KiCad symbol for the XIAO nRF52840. However, I noticed the symbol you created is incomplete and seems to be missing some key information compared to the official XIAO KiCad library files we maintain.

Below:
[Seeed_Studio_XIAO_Series.zip](https://github.com/Seeed-Studio/OPL_Kicad_Library/files/15428355/Seeed_Studio_XIAO_Series.zip)

**Comment by ndoo** [comment]
Sounds like Seeed needs to sync up internally to put the newest files here?
As I use this repo as a git submodule

**Pull request merged**
